export const userDetils = [{
   id: 1,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/439697a.jpg?ts=1644840288",
   price: 110,
   title: "Amul Blend Diced Cheese",
   weight: "100gm",
},
{
   id: 2,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/10491a.jpg",
   title: "Nested Milkmaid",
   weight: "300gm",
   price: "207",
},
{
   id: 3,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/45533a.jpg?ts=1654845569",
   title: "Amul Masti Crud",
   weight: "250gm",
   price: "307",
},
{
   id: 4,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/483705a.jpg?ts=1657805510",
   title: "Table White Eggs",
   weight: "500gm",
   price: "120",
},
{
   id: 5,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/19512a.jpg?ts=1647923044",
   title: "Amul Fresh Milk",
   weight: "250gm",
   price: "40",
}, {
   id: 6,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/95609a.jpg?ts=1625639870",
   price: 110,
   title: "Harvest Gold Sandwich Bread",
   weight: "500gm",
},
{
   id: 7,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/46256a.jpg",
   title: "Saras Gold Full Cream Fresh Milk",
   weight: "500gm",
   price: "50",
},
{
   id: 8,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/125240a.jpg?ts=1654778894",
   title: "Amul Cheese Slices",
   weight: "250gm",
   price: "78",
},
{
   id: 9,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/10492a.jpg",
   title: "Amul Mithai Mate Condensed Milk",
   weight: "500gm",
   price: "120",
},
{
   id: 5,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/19512a.jpg?ts=1647923044",
   title: "Amul Fresh Milk",
   weight: "250gm",
   price: "40",
},
{
   id: 7,
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/46256a.jpg",
   title: "Saras Gold Full Cream Fresh Milk",
   weight: "500gm",
   price: "50",
},
{
   id: 8,   
   image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=135/app/images/products/sliding_image/125240a.jpg?ts=1654778894",
   title: "Amul Cheese Slices",
   weight: "250gm",
   price: "78",
},


]