export const catagiryOffer=[{id:"1",image:"https://mishry.com/wp-content/uploads/2022/05/blinkit-packaging.jpg",logo:"paan corner"},
{id:"2", image:"https://www.foodspark.io/images/blog/December/How-Web-Scraping-is-Used-to-Deliver-Blink-it-Grocery-Delivery-Data/Business-Expansion.jpg",logo:"Dairy Bread & Eggs"},
{id:"3", image:"https://d168jcr2cillca.cloudfront.net/uploadimages/coupons/14851-Blinkit-Offers-Coupons-1.jpg",logo:"Fruits & Vegitable"},
{id:"4", image:"https://kj1bcdn.b-cdn.net/media/59629/mothers-choice.jpg",logo:"Cold Drinks & Juics"},
{id:"5", image:"https://kj1bcdn.b-cdn.net/media/59629/mothers-choice.jpg",logo:"Snaks & Munices"},
{id:"6", image:"https://www.foodspark.io/images/blog/December/How-Web-Scraping-is-Used-to-Deliver-Blink-it-Grocery-Delivery-Data/Business-Expansion.jpg",logo:"Breakfast & instant food"},
{id:"7", image:"https://kj1bcdn.b-cdn.net/media/59629/mothers-choice.jpg",logo:"Sweet Tooth"},
{id:"8", image:"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=50,metadata=none,w=360/app/images/products/sliding_image/329500a.jpg?ts=1662964180",logo:"Bekery & Biscuties"},
{id:"9", image:"https://kj1bcdn.b-cdn.net/media/59629/mothers-choice.jpg",logo:"Tea,Coffie & Health Drink"},
{id:"10", image:"https://www.hi5mart.com/image/cache/catalog/Dairy/Amul%20Malai%20Panee-200x200.png",logo:"Atta & Rice"},
{id:"11", image:"https://kj1bcdn.b-cdn.net/media/59629/mothers-choice.jpg",logo:"Sauces"},
{id:"12", image:"https://taazao.com/img/SBC_New/taazao_SBC_BakeryDairyEggs_1024X1024.png",logo:"oil"},
{id:"13",image:"https://kj1bcdn.b-cdn.net/media/59629/mothers-choice.jpg",logo:"Chicken & Meet"},
{id:"14",image:"https://images.myboxed.com.my/unsafe/filters:quality(100):max_bytes(50000)/https://assets.myboxed.com.my/r512x400_1674706824782.jpg",logo:"Baby Carrer"},
{id:"15", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6AJmDWe5MSDYnb1Uor6VZzduG9BAmeEbJAGiyy_3pNMg65UvlrfX00z2n82SDx2zaKub_b-0fW60&usqp=CAU&ec=48600113",logo:"Cleaning eqp."},
{id:"16",image:"https://mishry.com/wp-content/uploads/2022/05/zepto-vs-blinkit-overview.jpg",logo:"paan corner"},
{id:"17",image:"https://mishry.com/wp-content/uploads/2022/05/blinkit-packaging.jpg",logo:"Home & Office"},]